markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

permalink: /:year/:month/:day/:title.html
excerpt_separator: ""

google_analytics_id: UA-12936734-2
#google_site_verification: google96ddd296d137fe13

timezone: America/New_York

collections:
  docs:
    output: true

name: David Sommers Blog
description: My blog
url: http://davidsommers.com

paginate: 3

plugins:
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
