markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

permalink: /:year/:month/:day/:title.html
excerpt_separator: ""

#google_site_verification: google96ddd296d137fe13

timezone: America/New_York

collections:
  docs:
    output: true

name: David Sommers Blog
description: >-
  David Sommers on software engineering, web performance, and the occasional
  yak shave.
url: https://davidsommers.com

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
